### Register
# @name register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "ofek1",
  "password": "123456"
}

###

### Login
# @name login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "ofek1",
  "password": "123456"
}

###

### Me (Protected) - uses token from login
GET http://localhost:3000/me
Authorization: Bearer {{login.response.body.token}}
